### ISSUE TITLE
[feature, not bug] rss订阅的bug

### ISSUE THREAD

**Issue by senseab** [leosongwei/blog#1]
![wp_20160929_09_55_58_pro](https://cloud.githubusercontent.com/assets/2174238/18938488/6b36cdce-862b-11e6-843d-ab5e30b63e8a.jpg)

**Comment by leosongwei** [comment]
是的，这是一个feature，不是bug。所有更新过的文章，都会被重新发表一次。

**Comment by leosongwei** [comment]
为了做成这样，我专门把guid设置成了帖子url+时间，好让每次提交后都被RSS阅读器认成是新的文章。
